- hosts: all
  user: centos
  become: yes
  become_user: root
  vars:
    hostname: c05077a
    domain_name: sysadexam.cs.ut.ee
    ip_address: 172.17.90.238
    ip_last_number: 238
    ip_reverse_all: 238.90.17.172
    ip_reverse_three: 90.17.172
    reverse_addr: in-addr.arpa
    serial_update: 2023053001
    mysql_root_password: "mariparool"
    mysql_db: "WordPress"
    mysql_user: "admin"
    mysql_admin_password: "pass"
    roundcube_db: "roundcubemail"
    roundcube_user: "roundcube"
    roundcube_pass: "inyfqoThaZwEnV6aWrDC+g=="

  roles:
          - { role: firewalls, tags: firewalls }
          - { role: etais, tags: etais }
          - { role: dns, tags: dns }
          - { role: apache, tags: apache }
          - { role: email, tags: email }
          - { role: tls, tags: tls }
          - { role: filesys, tags: filesys }
          - { role: container, tags: container }
          - { role: devops, tags: devops }
          - { role: kubernetes, tags: kubernetes }
          - { role: monit, tags: monit }
          - { role: tier1, tags: tier1 }

  tasks:
  - name: Testing this out
    debug: msg="Hello from user {{ ansible_user_id }} on server {{ ansible_hostname }}!"
