apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvol-lab11
spec:
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /shares/k8s
    server: c05077.sa.cs.ut.ee
    readOnly: false
