- name: Change root password
  user:
          name: root
          update_password: always
          password: $6$rounds=656000$5aWUEOwmQKXhsgui$IBmy7RLwETq4zz0FLrxWAnMh1KE1fsEo7YHqMxg6oPd.4Q95EqDPAz06yGktEVtJH9nl24YK24hYGGmJDq0pb
