- name: Copy the yaml files
  copy:
    src: "{{ item }}"
    dest: /home/centos/monitoring_lab/{{ item }}
  loop:
    - node-exporter.yaml
    - grafana.yaml
    - loki.yaml

- name: prometheus.yaml file for ip
  template:
    src: prometheus.j2
    dest: /home/centos/monitoring_lab/prometheus.yaml

- name: promtail.yaml file for ip
  template:
    src: promtail.j2
    dest: /home/centos/monitoring_lab/promtail.yaml
