- name: upgrade all packages
  pause:

- name: DNS | Autoremove unneeded packages installed as dependencies
  pause:

- name: Disable IPv6
  copy:
    src: 70-ipv6.conf
    dest: /etc/sysctl.d/70-ipv6.conf
    owner: root
    group: root
    mode: '0644'

- name: Change net.ipv6.conf.default.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.default.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Change net.ipv6.conf.all.disable_ipv6 to 1.
  sysctl:
    name: net.ipv6.conf.all.disable_ipv6
    value: '1'
    sysctl_file: /etc/sysctl.d/70-ipv6.conf
    reload: yes

- name: Inserts into hostname
  template:
    src: hostname.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: '0644'

- name: Inserts into hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    owner: root
    group: root
    mode: '0644'

- name: Install BIND package
  dnf:
    name: 
      - bind
      - bind-utils
    state: latest

- name: Create log directory into /var/named
  file:
    path: /var/named/log
    state: directory
    owner: named
    group: named
    mode: '0755'

- name: Create required log files
  file:
    path: /var/named/log/{{ item }}
    state: touch
    owner: named
    group: named
    mode: '0644'
  with_items:
  - default
  - auth_servers
  - zone_transfers
  - client_security
  - queries
  - query-errors

- name: Edit the DNS config file named.conf
  template:
    src: named.conf.j2
    dest: /etc/named.conf
    owner: root 
    group: named
    mode: '0640'

- name: Edit the resolv.conf file
  template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: '0644'

- name: Fill out the zone mappings
  template:
    src: zone.j2
    dest: /etc/named/{{ hostname}}.{{ domain_name }}
    owner: root
    group: root
    mode: '0644'

- name: Fill out the reverse zone mappings
  template:
    src: reverse_zone.j2
    dest: /etc/named/{{ ip_reverse_all }}.{{ reverse_addr }}
    owner: root
    group: root
    mode: '0644'

- name: Start and enable the named service
  service:
    name: named
    state: started
    enabled: yes
